In [33]:
import numpy as np
from tabulate import tabulate

#### Задана матриця:

In [34]:
task_array = [[ 3, 3, 8, 3, 10, 10, 6, 5, 4, 6, 3, 6],
              [ 3, 2, 8, 3, 2, 6, 6, 5, 4, 6, 3, 3],
              [ 10, 6, 8, 3, 10, 10, 10, 5, 7, 6, 8, 10],
              [ 1, 5, 4, 3, 1, 8, 10, 4, 7, 4, 8, 9],
              [ 6, 6, 8, 3, 10, 10, 10, 5, 7, 6, 8, 9],
              [ 7, 9, 8, 9, 10, 10, 10, 8, 7, 6, 8, 9],
              [ 3, 3, 6, 3, 1, 5, 6, 5, 4, 6, 3, 5],
              [ 5, 9, 10, 4, 1, 5, 10, 5, 4, 8, 3, 6],
              [ 1, 2, 4, 3, 1, 5, 7, 4, 4, 4, 3, 3],
              [ 5, 6, 8, 8, 2, 10, 7, 7, 4, 4, 3, 4],
              [ 7, 9, 8, 9, 10, 10, 10, 8, 7, 6, 8, 9],
              [ 8, 9, 8, 9, 10, 10, 10, 8, 8, 6, 8, 9],
              [ 7, 7, 8, 6, 2, 1, 4, 5, 6, 6, 2, 6],
              [ 1, 3, 6, 4, 2, 1, 4, 4, 3, 3, 2, 6],
              [10, 6, 8, 6, 10, 10, 10, 8, 7, 6, 10, 10],
              [10, 6, 8, 6, 10, 10, 10, 8, 8, 6, 10, 10],
              [ 7, 3, 8, 6, 5, 7, 7, 8, 4, 4, 1, 1],
              [ 8, 8, 8, 10, 6, 7, 10, 8, 4, 4, 10, 9],
              [ 1, 3, 2, 4, 2, 1, 4, 4, 3, 3, 2, 6],
              [ 1, 3, 2, 4, 2, 1, 2, 4, 3, 3, 2, 3]]


#### Формування множини векторів сигма

In [35]:
#виконуємо порівняння двох альтернатив
def compare_alternatives ( a1, a2):
    comparison_result = np.arange(len(a1))
    for i in range(0, len(a1)):
        if a1[i] > a2[i]:
            comparison_result[i] = 1
            continue
        elif a1[i] < a2[i]:
            comparison_result[i] = -1
            continue
        elif a1[i] == a2[i]:
            comparison_result[i] = 0
    return comparison_result

#формуємо множину векторів сигма попарним порівнянням альтернатив
def sigma_vectors(matrix):
    alternatives = np.array(matrix)
    result_matrix = [[0]*20 for i in range(20)]
    for i in range(0, 20):
        for j in range(0, 20):
            result_matrix[i][j] = compare_alternatives(alternatives[i], alternatives[j])
    return result_matrix

s_v = sigma_vectors(task_array)
s_v

[[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
  array([0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1]),
  array([-1, -1,  0,  0,  0,  0, -1,  0, -1,  0, -1, -1]),
  array([ 1, -1,  1,  0,  1,  1, -1,  1, -1,  1, -1, -1]),
  array([-1, -1,  0,  0,  0,  0, -1,  0, -1,  0, -1, -1]),
  array([-1, -1,  0, -1,  0,  0, -1, -1, -1,  0, -1, -1]),
  array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1]),
  array([-1, -1, -1, -1,  1,  1, -1,  0,  0, -1,  0,  0]),
  array([ 1,  1,  1,  0,  1,  1, -1,  1,  0,  1,  0,  1]),
  array([-1, -1,  0, -1,  1,  0, -1, -1,  0,  1,  0,  1]),
  array([-1, -1,  0, -1,  0,  0, -1, -1, -1,  0, -1, -1]),
  array([-1, -1,  0, -1,  0,  0, -1, -1, -1,  0, -1, -1]),
  array([-1, -1,  0, -1,  1,  1,  1,  0, -1,  0,  1,  0]),
  array([ 1,  0,  1, -1,  1,  1,  1,  1,  1,  1,  1,  0]),
  array([-1, -1,  0, -1,  0,  0, -1, -1, -1,  0, -1, -1]),
  array([-1, -1,  0, -1,  0,  0, -1, -1, -1,  0, -1, -1]),
  array([-1,  0,  0, -1,  1,  1, -1, -1,  0,  1,  1,  1]),
  array([-1, -1,  0, -1,  1,  1, 

#### Максимальні та найбільші за P та R та допоміжні функції (визначення симетричної, асиметричної, непорівнюваної частин)

In [36]:
#симетрична частина
def I(r):
    return (r==r.T)*r
#асиметрична частина
def P(r):
    return r-I(r)

#відношення непорівнюваності
def N(r):
    return (r==r.T)-I(r)

#найбільші по Р
def dom_max_p(m):
    matrix = np.array(m)
    max_ = []
    for i in range(0, len(matrix)):
        if matrix[i][i]==0 and matrix[i].sum()==len(matrix)-1:
            max_.append(i+1)
    return max_

# найбільші по R
def dom_max_r(m):
    matrix = np.array(m)
    max_ = []
    strong_max = []
    for i in range(0, len(matrix)):
        if matrix[i].sum()==len(matrix):
            max_.append(i+1)
            if matrix[:,i].sum()==1:
                strong_max.append(i+1)
    return max_, strong_max

#максимальні по Р
def block_max_p(m):
    matrix = np.array(m)
    max_ = []
    for i in range(0, len(matrix)):
        if matrix[:,i].sum()==0:
            max_.append(i+1)
    return max_

# максимальні по R
def block_max_r(m):
    matrix = np.array(m)
    sym = I(matrix)
    max_ = []
    strong_max = []
    for i in range(0, len(matrix)):
        if np.any(np.array_equal(matrix[:,i], sym[:,i])==False)==False:
            max_.append(i+1)
            if matrix[:,i].sum()==1 and matrix[i][i]==1:
                strong_max.append(i+1)
    return max_, strong_max
    
#перевірка на симетричність
def check_symetric_part(matrix):
    sym = I(np.array(matrix))
    flag = False
    for i in range(0, len(sym)):
        if sym[i].sum()>0:
            flag = True
            break
    return flag

#виведення найбільших/максимальних елементів
def print_max_element(matrix):
    #якщо симетрична частиа наявна - найбільші та максимальні по R
    if check_symetric_part(matrix):
        m, sm = dom_max_r(matrix)
        if len(m)>0:        
            print("Найбільші за R: {}".format(m))
            print("Строго найбільші за R: {}".format(sm))
        else:
            m, sm = block_max_r(matrix)
            print("Максимальні за R: {}".format(m))
            print("Строго максимальні за R: {}".format(sm))
    #якщо симетрична частина відсутня - найбільші та максимальні по Р
    else:
        if len(dom_max_p(matrix))>0:
            print("Найбільший за Р: {}".format(dom_max_p(matrix)))
        else:
            print("Максимальні за Р: {}".format(block_max_p(matrix)))

#### Відношення Парето

In [37]:
def pareto_check_vector(vector):
    check = np.array(vector)
    flag = True
    for i in range (0, len(check)):
        #усі елементи сигма-вектора невід'ємні
        if check[i]>=0:
            pass
        else:
            flag = False
    if flag:
        return 1
    else:
        flag = True
        for i in range (0, len(check)):
            #усі елементи сигма-вектора недодатні
            if check[i]<=0:
                pass
            else:
                flag = False
        if flag:
            return 2
        else:
            #сигма вектор містить як від'ємні, так і невід'ємні компоненти
            return 3
    
def pareto(sigma_vectors):
    vectors_matrix = np.array(sigma_vectors)
    result_matrix = [[0]*20 for i in range(20)]
    for i in range(0, 20):
        result_matrix[i][i] = 1
    for i in range(0, len(vectors_matrix)):
        for j in range(i+1, len(vectors_matrix)):
            flag = pareto_check_vector(vectors_matrix[i][j])
            # якщо елементи вектора невід'ємні - пара альтернатив належить відношенню, симетрична не належить
            if flag == 1:
                result_matrix[i][j] = 1
                result_matrix[j][i] = 0
                continue
            # якщо елементи вектора недодатні - пара альтернатив не належить відношенню, симетрична належить
            elif flag == 2:
                result_matrix[i][j] = 0
                result_matrix[j][i] = 1
                continue
            # інакше відношення та симетричне йому не належать множині
            elif flag == 3:
                result_matrix[i][j] = 0
                result_matrix[j][i] = 0   
    f = open("task6.txt", "w")
    f.write(" 1" + '\n')
    for i in range(0,len(result_matrix)):
        for j in range(0,len(result_matrix)):
            f.write(" {} ".format(result_matrix[i][j]))
        f.write('\n')
    f.close()
    return result_matrix


print_max_element(pareto(s_v))
pareto(s_v)

Максимальні за R: [8, 12, 16, 18]
Строго максимальні за R: [8, 12, 16, 18]


[[1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,

#### Мажоритарне відношення

In [38]:
def majority(sigma_vectors):
    vectors_matrix = np.array(sigma_vectors)
    result_matrix = [[0]*20 for i in range(20)]
    for i in range(0,len(vectors_matrix)):
        for j in range (i,len(vectors_matrix)):
            # якщо сума елементів сигма-вектора > 0 - пара альтернатив належить відношенню, симетричне не належить 
            if vectors_matrix[i][j].sum()>0:
                result_matrix[i][j]=1
                result_matrix[j][i]=0
                continue
            # якщо сума елементів сигма-вектора < 0 - пара альтернатив не належить відношенню, симетрична належить
            elif vectors_matrix[i][j].sum()<0:
                result_matrix[i][j]=0
                result_matrix[j][i]=1
                continue
            # якщо сума елементів сигма-вектора = 0 - пара альтернатив та симетричне ій не належать відношенню 
            elif vectors_matrix[i][j].sum()==0:
                result_matrix[i][j]=0
                result_matrix[j][i]=0
    f = open("task7.txt", "w")
    f.write(" 2" + '\n')
    for i in range(0,len(result_matrix)):
        for j in range(0,len(result_matrix)):
            f.write(" {} ".format(result_matrix[i][j]))
        f.write('\n')
    f.close()
    return result_matrix

print_max_element(majority(s_v))
majority(s_v)

Найбільший за Р: [16]


[[0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,

#### Лексикографічне відношення

In [39]:
#k5>k6>k4>k3>k9>k2>k8>k1>k12>k7>k10>k11
#k5>k8>k6>k2>k4>k1>k10>k3>k9>k11>k12>k7
# строге впорядкування критеріїв у векторі відповідно до варіанту
def sort_strong_order(a):
    ordered = np.arange(len(a))
    #order = np.array([ 4, 5, 3, 2, 8, 1, 7, 0, 11, 6, 9, 10])
    order = np.array([ 4, 7, 5, 1, 3, 0, 9, 2, 8, 10, 11, 6])
    for i in range (0, len(a)):
        ordered[i]=a[order[i]]
    return ordered

# впорядкування критеріїв у всіх векторах
def sort_sigma_vectors(sigma_vectors):
    vector_matrix = np.array(sigma_vectors)
    sorted_matrix = [[0]*20 for i in range(20)]
    for i in range(0,len(vector_matrix)):
        for j in range(0,len(vector_matrix)):
            sorted_matrix[i][j] = sort_strong_order(vector_matrix[i][j])
    return sorted_matrix

def lexicographic(matrix):
    sorted_vectors = np.array(matrix)
    result_matrix = [[0]*20 for i in range(20)]
    for i in range (0, len(result_matrix)):
        result_matrix[i][i]=0
    for i in range(0, len(sorted_vectors)):
        for j in range(i+1, len(sorted_vectors)):
            # Розглядаємо сигма-вектор для пари альтернатив ai aj
            a = sorted_vectors[i][j]
            for k in range(0, len(a)):
                # якщо ai переважає aj за критерієм k, пара ai aj належить відношенню, симетрична не належить
                if a[k]==1:
                    result_matrix[i][j]=1
                    result_matrix[j][i]=0
                    break
                # якщо aj переважає ai за критерієм k, пара ai aj не належить відношенню, симетрична належить
                elif a[k]==-1:
                    result_matrix[i][j]=0
                    result_matrix[j][i]=1
                    break
                # якщо альтернативи рівні за критерієм, переходимо до менш важливого критерію
                else:
                    continue
    f = open("task8.txt", "w")
    f.write(" 3" + '\n')
    for i in range(0,len(result_matrix)):
        for j in range(0,len(result_matrix)):
            f.write(" {} ".format(result_matrix[i][j]))
        f.write('\n')
    f.close()
    return result_matrix

print_max_element(lexicographic(sort_sigma_vectors(s_v)))
lexicographic(sort_sigma_vectors(s_v))
            

Найбільший за Р: [12]


[[0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1],
 [0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,

#### Відношення Березовського

In [40]:
#{k5,k8,k11,k12} < {k3,k4} < {k1,k2,k6,k7,k9,k10}

#{k1,k2,k8,k11} < {k4,k5,k12} < {k3,k6,k7,k9,k10}
def set_vectors(a):
    select1 = np.array([ 0, 0, 0, 0, a[4], 0, 0, a[7], 0, 0, a[10], a[11]])
    select2 = np.array([ 0, 0, a[2], a[3], 0, 0, 0, 0, 0, 0, 0, 0]) 
    select3 = np.array([ a[0], a[1], 0, 0, 0, a[5], a[6], 0, a[8], a[9], 0, 0])
    return select1, select2, select3

def div_vectors_into_classes(sigma_vectors):
    vectors_matrix = np.array(sigma_vectors)
    class1_matrix = [[0]*20 for i in range(20)]
    class2_matrix = [[0]*20 for i in range(20)]
    class3_matrix = [[0]*20 for i in range(20)]
    for i in range(0,20):
        for j in range(0,20):
            a = vectors_matrix[i][j]
            class1_matrix[i][j], class2_matrix[i][j], class3_matrix[i][j] = set_vectors(a)      
        
    return class1_matrix, class2_matrix, class3_matrix

def berezovskiy(sigma_vectors):
    # Pb1, Ib1, Nb1
    iter1_p = [[0]*20 for i in range(20)]
    iter1_i = [[0]*20 for i in range(20)]
    iter1_n = [[0]*20 for i in range(20)]
    # Pb2 (результуюче відношення)
    result_matrix = [[0]*20 for i in range(20)]
    # розбиваємо критерії на класи. с1 - найменш важливий
    c1,c2,c3=div_vectors_into_classes(s_v)
    pareto1 = np.array(pareto(c1))
    pareto2 = np.array(pareto(c2))
    pareto3 = np.array(pareto(c3))
    # виділяємо для кожного класу симетричну, асиметричну та непорівнювану частини відношення Парето
    # I01, P01, N01 (приймаємо за Ib0, Pb0, Nb0)
    i1 = I(pareto1)
    p1 = P(pareto1)
    n1 = N(pareto1)
    # I02, P02, N02
    i2 = I(pareto2)
    p2 = P(pareto2)
    n2 = N(pareto2)
    #I03, P03, N03
    i3 = I(pareto3)
    p3 = P(pareto3)
    n3 = N(pareto3)
    
    # Формуємо Pb1, Ib1, Nb1
    for i in range(0,len(result_matrix)):
        for j in range(0, len(result_matrix)):
            if p2[i][j]==1 and p2[i][j]==p1[i][j]:
                iter1_p[i][j]=1            
            if p2[i][j]==1 and p2[i][j]==n1[i][j]:
                iter1_p[i][j]=1            
            if i2[i][j]==1 and i2[i][j]==p1[i][j]:
                iter1_p[i][j]=1
            if p2[i][j]==1 and p2[i][j]==i1[i][j]:
                iter1_p[i][j]=1
#             if i2[i][j]==1 and i2[i][j]==i1[i][j]:
#                 iter1_i[i][j]=1 
    for i in range(0,len(result_matrix)):
        for j in range(0, len(result_matrix)):
            if iter1_p[i][j]==0 and iter1_i[i][j]==0:
                iter1_n[i][j]==1
    # Формуємо Pb2 (результат) порівнюючи I03, P03, N03 з Pb1, Ib1, Nb1
    for i in range(0,len(result_matrix)):
        for j in range(0, len(result_matrix)):
            if p3[i][j]==1 and p3[i][j]==iter1_p[i][j]:
                result_matrix[i][j]=1            
            if p3[i][j]==1 and p3[i][j]==iter1_n[i][j]:
                result_matrix[i][j]=1            
            if i3[i][j]==1 and i3[i][j]==iter1_p[i][j]:
                result_matrix[i][j]=1
            if p3[i][j]==1 and p3[i][j]==iter1_i[i][j]:
                result_matrix[i][j]=1  
    f = open("task9.txt", "w")
    f.write(" 4" + '\n')
    for i in range(0,len(result_matrix)):
        for j in range(0,len(result_matrix)):
            f.write(" {} ".format(result_matrix[i][j]))
        f.write('\n')
    f.close()
    return result_matrix

print_max_element(berezovskiy(s_v))
berezovskiy(s_v)

Максимальні за Р: [6, 8, 12, 15, 16, 18]


[[0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,

#### Відношення Подиновського

In [41]:
# сортування значень критеріїв за спаданням
def psi_alternatives(matrix):
    alternatives = np.array(matrix)
    for i in range(0,20):
        a=alternatives[i]
        a[::-1].sort()
        alternatives[i] = a
    return alternatives

def podynovskiy(matrix):
    # формування множини функції псі від альтернатив(сортування за спаданням)
    psi_a = psi_alternatives(matrix)
    # формування сигма-векторів побудованих для псі(аі)
    sv = sigma_vectors(psi_a)
    # відношення Парето для множини псі(аі)
    result_matrix = pareto(sv)   
    f = open("task10.txt", "w")
    f.write(" 5" + '\n')
    for i in range(0,len(result_matrix)):
        for j in range(0,len(result_matrix)):
            f.write(" {} ".format(result_matrix[i][j]))
        f.write('\n')
    f.close()
    return result_matrix

print_max_element(podynovskiy(task_array))
podynovskiy(task_array)

Максимальні за R: [12, 16]
Строго максимальні за R: [12, 16]


[[1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
 [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1],
 [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1],
 [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,