In [6]:
import numpy as np

In [7]:
#### Задана матриця:

In [8]:
task_array = [[ 3, 3, 8, 3, 10, 10, 6, 5, 4, 6, 3, 6],
              [ 3, 2, 8, 3, 2, 6, 6, 5, 4, 6, 3, 3],
              [ 10, 6, 8, 3, 10, 10, 10, 5, 7, 6, 8, 10],
              [ 1, 5, 4, 3, 1, 8, 10, 4, 7, 4, 8, 9],
              [ 6, 6, 8, 3, 10, 10, 10, 5, 7, 6, 8, 9],
              [ 7, 9, 8, 9, 10, 10, 10, 8, 7, 6, 8, 9],
              [ 7, 9, 8, 9, 10, 10, 10, 8, 7, 6, 8, 9],
              [ 7, 9, 8, 9, 10, 10, 10, 8, 7, 6, 8, 9],
              [ 3, 3, 6, 3, 1, 5, 6, 5, 4, 6, 3, 5],
              [ 5, 9, 10, 4, 1, 5, 10, 5, 4, 8, 3, 6],
              [ 1, 2, 4, 3, 1, 5, 7, 4, 4, 4, 3, 3],
              [ 1, 2, 4, 3, 1, 5, 7, 4, 4, 4, 3, 3],
              [ 5, 6, 8, 8, 2, 10, 7, 7, 4, 4, 3, 4],
              [ 7, 9, 8, 9, 10, 10, 10, 8, 7, 6, 8, 9],
              [ 8, 9, 8, 9, 10, 10, 10, 8, 8, 6, 8, 9],
              [ 7, 7, 8, 6, 2, 1, 4, 5, 6, 6, 2, 6],
              [ 1, 3, 6, 4, 2, 1, 4, 4, 3, 3, 2, 6],
              [10, 6, 8, 6, 10, 10, 10, 8, 7, 6, 10, 10],
              [ 7, 3, 8, 6, 5, 7, 7, 8, 4, 4, 1, 1],
              [ 8, 8, 8, 10, 6, 7, 10, 8, 4, 4, 10, 9],
              [ 1, 3, 2, 4, 2, 1, 4, 4, 3, 3, 2, 6],
              [ 1, 3, 2, 4, 2, 1, 2, 4, 3, 3, 2, 3]]

#### Формування множини векторів сигма

In [12]:
def compare_alternatives ( a1, a2):
    comparison_result = np.arange(len(a1))
    for i in range(0, len(a1)):
        if a1[i] > a2[i]:
            comparison_result[i] = 1
        elif a1[i] < a2[i]:
            comparison_result[i] = -1
        elif a1[i] == a2[i]:
            comparison_result[i] = 0
    return comparison_result

def sigma_vectors(matrix):
    alternatives = np.array(matrix)
    for i in range(0, 20):
        for j in range(0, 20):
            print(compare_alternatives(alternatives[i], alternatives[j]))

sigma_vectors(task_array)
    

[0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 1 1 0 0 0 0 0 1]
[-1 -1  0  0  0  0 -1  0 -1  0 -1 -1]
[ 1 -1  1  0  1  1 -1  1 -1  1 -1 -1]
[-1 -1  0  0  0  0 -1  0 -1  0 -1 -1]
[-1 -1  0 -1  0  0 -1 -1 -1  0 -1 -1]
[-1 -1  0 -1  0  0 -1 -1 -1  0 -1 -1]
[-1 -1  0 -1  0  0 -1 -1 -1  0 -1 -1]
[0 0 1 0 1 1 0 0 0 0 0 1]
[-1 -1 -1 -1  1  1 -1  0  0 -1  0  0]
[ 1  1  1  0  1  1 -1  1  0  1  0  1]
[ 1  1  1  0  1  1 -1  1  0  1  0  1]
[-1 -1  0 -1  1  0 -1 -1  0  1  0  1]
[-1 -1  0 -1  0  0 -1 -1 -1  0 -1 -1]
[-1 -1  0 -1  0  0 -1 -1 -1  0 -1 -1]
[-1 -1  0 -1  1  1  1  0 -1  0  1  0]
[ 1  0  1 -1  1  1  1  1  1  1  1  0]
[-1 -1  0 -1  0  0 -1 -1 -1  0 -1 -1]
[-1  0  0 -1  1  1 -1 -1  0  1  1  1]
[-1 -1  0 -1  1  1 -1 -1  0  1 -1 -1]
[ 0 -1  0  0 -1 -1  0  0  0  0  0 -1]
[0 0 0 0 0 0 0 0 0 0 0 0]
[-1 -1  0  0 -1 -1 -1  0 -1  0 -1 -1]
[ 1 -1  1  0  1 -1 -1  1 -1  1 -1 -1]
[-1 -1  0  0 -1 -1 -1  0 -1  0 -1 -1]
[-1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1]
[-1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1]
[-1 -1  0 -1 -1 -1 -1 